name: learn-github-docker-actions
  with: # Set the secret as an input
    dockerhub_secret: ${{ secrets.DOCKERHUB_SHLOMOKO_KEY }}
run-name: ${{ github.actor }} is learning docker GitHub Actions 
on: [push]
jobs:
  prepare-ubuntu-net-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker --version
      - run: docker build -t shlomoko11/ubuntunet:1.0 .
      - run: docker login --username shlomoko11  --password "$dockerhub_secret"
