name: learn-github-docker-actions
run-name: ${{ github.actor }} is learning docker GitHub Actions 
on: [push]
jobs:
  prepare-ubuntu-net-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker --version