name: learn-github-docker-actions
env: 
  docker_version: 1.1
  dockerhub_secret: ${{ secrets.DOCKERHUB_SHLOMOKO_KEY }}
run-name: ${{ github.actor }} is learning docker GitHub Actions 
on: [push]
jobs:
  prepare-ubuntu-net-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker --version
      - run: docker build -t shlomoko11/ubuntunet:"$docker_version" .
      - run: docker scan shlomoko11/ubuntunet:"$docker_version"
      - run: docker login --username shlomoko11  --password "$dockerhub_secret"
      - run: docker push  shlomoko11/ubuntunet:"$docker_version"
